import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "./components/Navebar/page";
import Footer from "./components/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{display:'flex'}}>
        <Navebar/>

        <div style ={{ marginLeft:'200px', width:'100%', padding:'20px'}}>
        {children}
        <Footer/>
        </div>
        </div>
        

      </body>
    </html>
  );
}
