import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "./components/Navebar/page";
import Footer from "./components/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="  bg-[#0f172a]"
      >
        <div style={{display:'flex'}} >
          <div className="w-73 h-screen fixed left-0 top-0 shadow-lg">
        <Navebar/>
        </div>

        <div className="ml-64 flex-1 min-h-screen flex-col  w-full flex items-center justify-center px-8 bg-[#020617] ">
         <main className="flex-grow p-6">{children}</main>
          </div>  
         </div>
        <Footer/>
        

      </body>
    </html>
  );
}
